language: go
go: 
  - "1.13"
  - "1.14"
  - "1.15"
  - "1.16"
  - "1.17"
  - "1.18"
  - "1.19"

before_install:
  - export GO111MODULE="on"
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go install github.com/axw/gocov/gocov
  - go install github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - if ! go install github.com/golang/tools/cmd/cover; then go install golang.org/x/tools/cmd/cover; fi

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
